# Publish devcontainer template artifacts. See them here: 
# https://github.com/orgs/multiversx/packages?repo_name=mx-template-devcontainers
# 
# - Package "mx-template-devcontainers": not versioned, tagged as "latest"
# - Package "smart-contracts-rust": versioned according to src/smart-contracts-rust/devcontainer-template.json

name: Publish templates

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Publish"
        uses: devcontainers/action@v1.3.0
        with:
          disable-repo-tagging: false
          publish-templates: true
          base-path-to-templates: "./src"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
